import os

# Liste des fichiers attendus
image_files = [
    "tartine_avocat_feta.jpg",
    "banana_bread.jpg",
    "pudding_chia.jpg",
    "brioche_tressee.jpg",
    "salade_fruits_frais.jpg",
    "pancakes_healthy.jpg",
    "porridge_healthy.jpg",
    "tajine_poulet_olives_citron.jpg",
    "cookies_banane_avoine.jpg",
    "green_smoothie.jpg",
    "tartines_saumon.jpg",
    "risotto_champignons_parmesan.jpg",
    "lasagnes_epinards_ricotta.jpg",
    "smoothie_bowl_acai.jpg",
    "wraps_oeufs_avocat.jpg",
    "tartiflette_light.jpg",
    "muffins_raisins.jpg",
    "barres_energetiques.jpg",
    "burger_lentilles_avocat.jpg",
    "poulet_tikka_masala.jpg",
    "tarte_tatin.jpg",
    "granola_noix_miel.jpg",
    "gratin_dauphinois.jpg",
    "clafoutis_cerises.jpg",
    "cheesecake_fruits_rouges.jpg",
    "paella_fruits_de_mer.jpg",
    "ratatouille_provencale.jpg",
    "quiche_lorraine.jpg",
    "fondant_chocolat.jpg",
    "crepes_suzette.jpg",
    "eclairs_cafe.jpg",
    "creme_brulee_vanille.jpg",
    "macarons_framboise.jpg",
    "bouchees_reine.jpg",
    "bruschetta_tomate_basilic.jpg",
    "energy_balls_dattes_noix.jpg",
    "caviar_aubergine.jpg",
    "tartare_saumon.jpg",
    "daiquiri_fraise.jpg",
    "panna_cotta_mangue.jpg",
    "bagels_saumon_cream_cheese.jpg",
    "pancakes_banane_chocolat.jpg",
    "smoothie_vert_avocat_epinards.jpg",
    "pain_perdu_cannelle.jpg",
    "omelette_epinards_feta.jpg",
    "mousse_chocolat.jpg",
    "smoothie_bowl_mangue_coco.jpg",
    "cafe_frappe.jpg",
    "cosmopolitan.jpg",
    "mojito_classique.jpg",
    "sangria_rouge.jpg",
    "chai_latte.jpg",
    "sangria_blanche.jpg",
    "limonade_maison.jpg",
    "biscuits_avoine_chocolat.jpg",
    "feuilletes_fromage_jambon.jpg",
    "spritz_aperol.jpg",
    "pina_colada.jpg",
    "chia_pudding_coco.jpg",
    "the_glace_peche.jpg",
    "cocktail_pasteque_menthe.jpg",
    "gin_tonic.jpg",
    "chips_legumes_maison.jpg",
    "ceviche_crevettes.jpg",
    "margarita.jpg",
    "avocado_toast_chia.jpg",
    "galettes_lentilles_corail.jpg",
    "pizza_vegetarienne.jpg",
    "omelette_norvegienne.jpg",
    "samossas_legumes.jpg",
    "tofu_teriyaki.jpg",
    "chili_sin_carne.jpg",
    "curry_pois_chiches_epinards.jpg",
    "smoothie_bowl_papaye_gingembre.jpg",
    "tartelettes_ratatouille.jpg",
    "buddha_bowl_legumes_rotis.jpg",
    "pancakes_patate_douce_cannelle.jpg",
    "rouleaux_printemps.jpg",
    "oeufs_toast_avocat_piment.jpg",
    "porridge_chai_latte_pommes.jpg",
    "petits_pains_curcuma_sesame.jpg",
    "granola_matcha_coco.jpg",
    "burger_poulet_curry_mangue.jpg",
    "tartines_pain_seigle_fromage_figues.jpg",
    "salade_quinoa_chevre_betterave.jpg",
    "brioche_chocolat_fleur_oranger.jpg",
    "crepes_farine_chataigne.jpg",
    "risotto_safran_fruits_mer.jpg",
    "tarte_courgettes_feta.jpg",
    "pates_gorgonzola_noix.jpg",
    "salade_nicoise_revisitee.jpg",
    "poke_bowl_saumon_edamame.jpg",
    "tarte_caramel_beurre_sale.jpg",
    "pho_vietnamien.jpg",
    "pain_epices_epices_douces.jpg",
    "sandwich_porc_effiloche_coleslaw.jpg",
    "financiers_matcha.jpg",
    "donuts_creme_patissiere.jpg",
    "tacos_crevettes_citron_vert.jpg",
    "biscuits_beurre_confiture.jpg",
    "gaufres_miel_noix.jpg",
    "lasagnes_bolognaise.jpg",
    "sushi_burger.jpg",
    "gratin_courgettes_tomates.jpg",
    "poulet_roti_herbes_provence.jpg",
    "couscous_vegetarien_legumes_rotis.jpg",
    "ramen_curry_poulet.jpg",
    "feijoada_vegetarienne.jpg",
    "pizza_margherita_maison.jpg",
    "fajitas_boeuf_oignons.jpg",
    "dahl_lentilles_corail_epinards.jpg",
    "pierogi_champignons_creme.jpg",
    "baklava_noix_miel.jpg",
    "buddha_bowl_quinoa_legumes.jpg",
    "tofu_marine_miso_sesame.jpg",
    "curry_lait_coco_legumes_rotis.jpg",
    "soupe_lentilles_corail_lait_coco.jpg",
    "tartelettes_legumes_feta.jpg",
    "gratin_chou_fleur_brocoli.jpg",
    "cheesecake_speculoos_caramel.jpg",
    "tarte_pommes_cannelle.jpg",
    "panna_cotta_cafe_caramel.jpg",
    "macarons_chocolat_framboise.jpg",
    "clafoutis_abricots_amandes.jpg",
    "omelette_champignons.jpg",
    "tartare_thon_avocat.jpg",
    "ceviche_dorade_mangue.jpg",
    "caviar_courgettes_feta.jpg",
    "burger_poisson_wasabi.jpg",
    "samossas_boeuf_epices.jpg",
    "tartelettes_ratatouille_chevre.jpg",
    "chips_kale_parmesan.jpg",
    "mini_quiches_poireaux_gorgonzola.jpg",
    "smoothie_bowl_banane_beurre_cacahuete.jpg",
    "oeufs_benedicte.jpg",
    "petits_pains_lait.jpg",
    "crepes_sarrasin_salees.jpg",
    "oeufs_cocotte_epinards_chevre.jpg",
    "burrito_boeuf_haricots.jpg",
    "tartines_pain_epices_fromage_frais.jpg",
    "salade_cesar_poulet_grille.jpg",
    "poke_bowl_thon_avocat.jpg",
    "cookies_pepites_chocolat_noix_pecan.jpg",
    "sandwich_cubain.jpg",
    "pates_pesto_basilic_pignons.jpg",
    "risotto_asperges_parmesan.jpg",
    "tacos_poisson_frit.jpg",
    "donuts_glaces.jpg",
    "pain_epices_moelleux.jpg",
    "biscuits_sables_vanille.jpg",
    "granola_chocolat_noisette.jpg",
    "soupe_miso_nouilles_soba.jpg",
    "gaufres_liegeoises.jpg",
    "brisket.jpg",
    "chocolat_chaud_epais.jpg",
    "bao_buns_porc_caramelise.jpg",
    "soupe_pois_casses_lard.jpg",
    "empanadas_poulet_poivrons.jpg",
    "chili_sin_carne_haricots_mais.jpg",
    "rouleaux_printemps_legumes.jpg",
    "pizza_vegetarienne_artichauts_olives.jpg",
    "galettes_pois_chiches_epinards.jpg",
    "bouchees_reine_champignons.jpg",
    "fondant_chocolat_menthe.jpg",
    "crepes_suzette_orange_grand_marnier.jpg",
    "brioche_perdue_vanille.jpg",
    "quiche_poireaux_saumon_fume.jpg",
    "gateau_yaourt_citron.jpg",
    "porridge_fruits_secs_miel.jpg",
    "financiers_amandes.jpg",
    "churros_chocolat_chaud.jpg",
    "tarte_citron_meringuee.jpg",
    "eclairs_caramel_beurre_sale.jpg",
    "bibimbap_tofu_legumes.jpg",
    "feuilletes_fromage_bleu_poires.jpg",
    "fondue_chocolat_fruits.jpg",
    "mousse_chocolat_fleur_sel.jpg",
    "croissants_maison.jpg",
    "curry_rouge_thai_porc.jpg",
    "tartiflette_reblochon_lardons.jpg",
    "faux-filet.jpg",
    "muffins_myrtilles.jpg",
    "salade_lentilles_feta.jpg"
]


# Dossier où les images ont été téléchargées
download_dir = "downloaded_images"

# Vérifier l'existence du dossier
if not os.path.exists(download_dir):
    print(f"Le dossier '{download_dir}' n'existe pas.")
    exit()

# Lister les fichiers présents dans le dossier
downloaded_files = set(os.listdir(download_dir))

# Trouver les fichiers manquants
missing_files = [f for f in image_files if f not in downloaded_files]

# Afficher les résultats
if missing_files:
    print(f"{len(missing_files)} fichiers manquants sur {len(image_files)} :")
    for file in missing_files:
        print(f"- {file}")
else:
    print("Tous les fichiers ont été téléchargés avec succès !")

# Optionnel : Sauvegarder la liste des fichiers manquants dans un fichier texte
with open("missing_files.txt", "w") as f:
    f.write("\n".join(missing_files))

print("La liste des fichiers manquants a été sauvegardée dans 'missing_files.txt'")